[project]
name = "library-manegment-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-generativeai>=0.8.4",
    "litellm>=1.63.7",
    "streamlit>=1.43.2",
]
